global:
  scrape_interval: 5s
scrape_configs:
#  Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
#  The json-exporter itself
  - job_name: json_exporter
    static_configs:
      - targets:
          - json-exporter:7979
#  CHT /monitoring endpoint (via json-exporter)
  - job_name: cht
    metrics_path: /probe
    params:
      module: [default]
    static_configs:
      - targets:
          - https://192-168-1-248.my.local-ip.co:10443/api/v2/monitoring
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json-exporter:7979
